travis:
  secure:
    BINSTAR_TOKEN: hUdQKx+1gwlzX1fKMwD26KdLiEa2pH5PT0VDL8uGXKD2mPSozjl7lTfNywt/C1k0N3JNB5i+6ZJv6aUijbUeCMXHHPYrdDJzsthSCDw3IiXjrYVZxWMS6qCbzmqRHm28rm9p+KeFdWnRPUNebqR+6IqJgwN8PRQPzeD4UeqetH4toRqSyydSGt0/SH+RHpf0/kJvbEW/+gfYKiTutrW6TEf86em3/qaeafR67lEgpq6YYw3AV1LPyOZan61nA7cVPvFrbYRlTwn9fZzVjNeDRwSspXWazs+K701yezB7dKnWjzRzEQmax/ykKlu5Tp76VCriU8edoVVJ8fQ/5exe8QHsZ0FScOPJt6Y5qkln0jme36h6CUksFD3NO19hj1Us3rhPfM6suEzge9LwxpabMCIwE+dS+Bt8ThSpCfCcTR8GIbIkPywaGQiYJOyf1NxOnm8w7vkURrp0aHrepYLCE/OkPevCbV59YqszeRzzKHDFcKhnoAGOdhuCnjLAaY0ZqglVFYRL8DODTQzt3VoRBvzSSOphZvTZ7DLPmBGmfmhSCl3WKP1NVsl39gysSt0bvrpRB/E0mPhkw9fQa2xT7fBEtgHf5vwWqBtdRfVt0rIJofLFqCbe1zCnGJN6uadi2WxkiQ9evuwRLmls0LHA2jTka+WcNzQVOgzPOIkdcuE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
